### ISSUE TITLE
Build failed after t dists addition

### ISSUE THREAD

**Issue by ryan-wolbeck** [stanfordmlgroup/ngboost#203]
@mzjp2 @angeldroth 

Unfortunately we arrived at another pip lock issue

```
Run python -m pip install --upgrade pip
Requirement already up-to-date: pip in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (20.2.4)
Collecting pre-commit
  Downloading pre_commit-2.8.2-py2.py3-none-any.whl (184 kB)
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.5.0-py2.py3-none-any.whl (21 kB)
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.1.0-py2.py3-none-any.whl (4.9 MB)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pyyaml>=5.1
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting identify>=1.0.0
  Downloading identify-1.5.9-py2.py3-none-any.whl (97 kB)
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.2.0-py2.py3-none-any.whl (7.3 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting filelock<4,>=3.0.0
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting appdirs<2,>=1.4.3
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting six<2,>=1.9.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Using legacy 'setup.py install' for pyyaml, since package 'wheel' is not installed.
Installing collected packages: nodeenv, distlib, filelock, appdirs, zipp, importlib-metadata, six, virtualenv, toml, pyyaml, identify, cfgv, pre-commit
    Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
Successfully installed appdirs-1.4.4 cfgv-3.2.0 distlib-0.3.1 filelock-3.0.12 identify-1.5.9 importlib-metadata-2.0.0 nodeenv-1.5.0 pre-commit-2.8.2 pyyaml-5.3.1 six-1.15.0 toml-0.10.2 virtualenv-20.1.0 zipp-3.4.0
Collecting pipenv
  Downloading pipenv-2020.11.4-py2.py3-none-any.whl (3.9 MB)
Collecting certifi
  Downloading certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied: virtualenv in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from pipenv) (20.1.0)
Requirement already satisfied: setuptools>=36.2.1 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from pipenv) (47.1.0)
Collecting virtualenv-clone>=0.2.5
  Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)
Requirement already satisfied: pip>=18.0 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from pipenv) (20.2.4)
Requirement already satisfied: six<2,>=1.9.0 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from virtualenv->pipenv) (1.15.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from virtualenv->pipenv) (1.4.4)
Requirement already satisfied: filelock<4,>=3.0.0 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from virtualenv->pipenv) (3.0.12)
Requirement already satisfied: importlib-metadata<3,>=0.12; python_version < "3.8" in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from virtualenv->pipenv) (2.0.0)
Requirement already satisfied: distlib<1,>=0.3.1 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from virtualenv->pipenv) (0.3.1)
Requirement already satisfied: zipp>=0.5 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from importlib-metadata<3,>=0.12; python_version < "3.8"->virtualenv->pipenv) (3.4.0)
Installing collected packages: certifi, virtualenv-clone, pipenv
Successfully installed certifi-2020.11.8 pipenv-2020.11.4 virtualenv-clone-0.5.4
Creating a virtualenv for this project...
Pipfile: /home/runner/work/ngboost/ngboost/Pipfile
Using /opt/hostedtoolcache/Python/3.7.9/x64/bin/python3.7 (3.7.9) to create virtualenv...
created virtual environment CPython3.7.9.final.0-64 in 488ms
  creator CPython3Posix(dest=/home/runner/.local/share/virtualenvs/ngboost-TXPYP4hW, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/runner/.local/share/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator


Successfully created virtual environment!
Virtualenv location: /home/runner/.local/share/virtualenvs/ngboost-TXPYP4hW
Installing dependencies from Pipfile.lock (ebf08d)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
Installing dependencies from Pipfile.lock (ebf08d)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
Installing -e ....

Adding ngboost to Pipfile's [packages]...

Installation Succeeded
Pipfile.lock (ebf08d) out of date, updating to (4dc867)...
Locking [dev-packages] dependencies...

Building requirements...

Resolving dependencies...

FAIL
[DependencyConflict]:   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/resolver.py", line 759, in main
[DependencyConflict]:       parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
[DependencyConflict]:   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/resolver.py", line 741, in _main
[DependencyConflict]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
[DependencyConflict]:   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/resolver.py", line 714, in resolve_packages
[DependencyConflict]:       results = clean_results(results, resolver, project)
[DependencyConflict]:   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/resolver.py", line 596, in clean_results
[DependencyConflict]:       entry_dict = translate_markers(entry.get_cleaned_dict(keep_outdated=False))
[DependencyConflict]:   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/resolver.py", line 239, in get_cleaned_dict
[DependencyConflict]:       self.validate_constraints()
[DependencyConflict]:   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/resolver.py", line 536, in validate_constraints
[DependencyConflict]:       raise DependencyConflict(msg)
[pipenv.exceptions.DependencyConflict]: The operation failed... A dependency conflict was detected and could not be resolved.
ERROR: Cannot resolve conflicting version importlib-metadata==1.7.0 while importlib-metadata==2.0.0 is locked.


Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/utils.py", line 1116, in create_spinner
    yield sp
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/utils.py", line 1323, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pipenv/utils.py", line 1161, in resolve
    sys.exit(c.return_code)
SystemExit: 1

```

Does anyone have any ideas on this fix? I'm not comfortable at all with the curret pipenv implementation (I think we should remove it all together per the suggestion of @ecurtin2

**Comment by angeldroth** [comment]
Damn thats a massive pain

**Comment by mzjp2** [comment]
I’ll have a vetter look in a but, but my general feeling is that getting rid of pipenv is a goos thing, it seems oudated and unmaintained from my experience.

Either poetry, conda or plain venvs is my preference.

**Comment by angeldroth** [comment]
+1 for poetry or conda

**Comment by ryan-wolbeck** [comment]
@mzjp2 @angeldroth I'm personally a fan of poetry

**Comment by alejandroschuler** [comment]
Ouch... err... tbh I do all my development on bare metal like a heathen because I'm dumb and don't understand these things and every python package manager I've ever dipped my toe into has confused me and made me angry. So I'm not at all the best person to handle it. I would be ecstatic to see someone (literally anyone) take charge of this and remake it in their own godly image.

**Comment by ryan-wolbeck** [comment]
I'm looking at https://dephell.readthedocs.io/config.html (appropriately named) to do this conversion/fix

**Comment by mzjp2** [comment]
Whoops, only just seen your comment now @ryan-wolbeck, but for what it's worth, I've made significant progress in #204 after about 3 hours of heads down work :)
