### ISSUE TITLE
class CRPScore not defined?

### ISSUE THREAD

**Issue by rotcx** [stanfordmlgroup/ngboost#220]
`python
class CRPScore(Score):
    """
    Generic class for the continuous ranked probability scoring rule.
    """

CRPS = CRPScore
`

**Comment by rotcx** [comment]
/usr/local/bin/python3.7 ng/ngboost/examples/simulations/regression_sim.py
Traceback (most recent call last):
  File "ng/ngboost/ngboost/distns/distn.py", line 45, in implementation
    return {S.__bases__[-1]: S for S in scores}[Score]
KeyError: <ngboost.scores.CRPScore object at 0x11dbc26d0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "ng/ngboost/examples/simulations/regression_sim.py", line 45, in <module>
    verbose_eval=100,
  File "ng/ngboost/ngboost/ngboost.py", line 63, in __init__
    self.Manifold = manifold(Score, Dist)
  File "ng/ngboost/ngboost/manifold.py", line 12, in manifold
    class Manifold(Distribution.implementation(Score), Distribution):
  File "ng/ngboost/ngboost/distns/distn.py", line 48, in implementation
    f"The scoring rule {Score.__name__} is not "
AttributeError: 'CRPScore' object has no attribute '__name__'

**Comment by ryan-wolbeck** [comment]
@rotcx can you share your code?
