### ISSUE TITLE
AttributeError: 'NGBClassifier' object has no attribute 'classes_'

### ISSUE THREAD

**Issue by SamHosico** [stanfordmlgroup/ngboost#323]
when I use ngboost and sklearn, ngboost return a error:
AttributeError: 'NGBClassifier' object has no attribute 'classes_'
I have checked the lightGBM, it has the 'classes_', so I dont know how can I solve this problem, I need some help.
my code is as follows:

model = NGBClassifier(n_estimators=int(params['n_estimators'])
                          , learning_rate=params['learning_rate']
                          , minibatch_frac=params['minibatch_frac']
                          , col_sample=params['col_sample']
                          , Dist=Bernoulli
                          , verbose=False
                          , random_state=42)
   cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
   score = -cross_val_score(model, X_train, y_train.ravel(), cv=cv, scoring='roc_auc_ovo_weighted', error_score='raise').mean()### ###

**Comment by ryan-wolbeck** [comment]
Can you include what version you are using and provide a full example code with imports and loading a sample data like Iris: See below

from ngboost import NGBClassifier
from ngboost.distns import Bernoulli
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

X, y = load_iris(return_X_y=True)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**Comment by SamHosico** [comment]
> 
I found that when I use cross_ val_ score's "scoring='roc_ auc'", the program will give me an AttributeError: 'NGBClassifier' object does not have the attribute 'decision_function'.
However, I really want to use this metric to train my model, so I want to know how to change my code so that the NGBClassifier could create a function similar to 'decision_function'?

My code is as follows:
from ngboost import NGBClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
import warnings


X, y = load_breast_cancer(return_X_y=True)
X_cls_train, X_cls_test, Y_cls_train, Y_cls_test = train_test_split(X, y, test_size=0.2)
model = NGBClassifier(random_state=42, verbose=False)
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
score = cross_val_score(model, X_cls_train, Y_cls_train, scoring='roc_auc', cv=cv, error_score='raise')

**Comment by SamHosico** [comment]
> 
The error is as follows:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_scorer.py", line 359, in _score
    y_pred = method_caller(clf, "decision_function", X)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
AttributeError: 'NGBClassifier' object has no attribute 'decision_function'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\deep_learning_mot\Track_verification_device\bayes_opt\ngboost_t.py", line 11, in <module>
    score = cross_val_score(model, X_cls_train, Y_cls_train, scoring='roc_auc', cv=cv, error_score='raise')
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 515, in cross_val_score
    cv_results = cross_validate(
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 266, in cross_validate
    results = parallel(
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\joblib\parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\utils\fixes.py", line 117, in __call__
    return self.function(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 708, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer, error_score)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_scorer.py", line 106, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_scorer.py", line 376, in _score
    y_pred = self._select_proba_binary(y_pred, clf.classes_)
AttributeError: 'NGBClassifier' object has no attribute 'classes_'

**Comment by SamHosico** [comment]
> Can you include what version you are using and provide a full example code with imports and loading a sample data like the Boston data?
Thanks for your reply! I have rewritten a function to replace cross validation in sklearn using the 'roc_auc' to train my model, I have achieved the expected results.
