### ISSUE TITLE
indentation is broken in api.py

### ISSUE THREAD

**Issue by omarwagih** [stanfordmlgroup/ngboost#73]
I believe the indentation is broken as of the last commit. 

```
>>> from ngboost import NGBRegressor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/omarwagih/miniconda2/envs/pred_dpsi/lib/python3.8/site-packages/ngboost/__init__.py", line 2, in <module>
    from .api import NGBClassifier, NGBRegressor, NGBSurvival
  File "/Users/omarwagih/miniconda2/envs/pred_dpsi/lib/python3.8/site-packages/ngboost/api.py", line 64
    super().__init__(Dist, Score, Base, natural_gradient, n_estimators, learning_rate,
    ^
IndentationError: expected an indented block
```
Can you please fix?

**Comment by themrzmaster** [comment]
i created a PL #74 for this

**Comment by alejandroschuler** [comment]
Thank you all for catching this so quickly- I forgot to test things after the merge. Very sorry about that!

It's now fixed: https://github.com/stanfordmlgroup/ngboost/pull/74
