### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by X1AOX1A** [stanfordmlgroup/ngboost#85]
When I run the NGBoost with CRPS score, there is always bring out an error like:

`$ python3 -m examples.empirical.regression --dataset=housing  --score=CRPS --natural
== Dataset=housing X.shape=(506, 13) CRPS/Normal

Traceback (most recent call last):

  File "//anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "//anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "/Users/apple/Desktop/ngboost-d0f1bc859eec255396d88e057625473da27b1f69/examples/empirical/regression.py", line 116, in <module>

    train_loss, val_loss = ngb.fit(X_train, y_train) #, X_val, y_val)

  File "/Users/apple/Desktop/ngboost-d0f1bc859eec255396d88e057625473da27b1f69/ngboost/ngboost.py", line 87, in fit

    grads = S.natural_grad(D, Y_batch)

  File "/Users/apple/Desktop/ngboost-d0f1bc859eec255396d88e057625473da27b1f69/ngboost/scores.py", line 26, in natural_grad

    grad = forecast.D_crps(Y)

TypeError: 'NoneType' object is not callable`

Could you plz help me with the problem?

**Comment by tonyduan** [comment]
Looks like you're using an outdated version of the codebase.

Could you try pulling and trying again?

`pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost.git`
